region = "global"                                                      # "global", "china". Defaults to "global".
product = "wow"                                                        # "wow", "wow_classic", "wow_classic_era". Defaults to "wow".
feature = "net"                                                        # "none", "net", "menu". Defaults to "net".
output_directory = "download"                                          # Defaults to "download".
mega_folder = "https://mega.nz/folder/XQdwFJTR#X8VNWdap7eKtIvmPbpW6sA"
